### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by tylerolson** [anesthetiize/SpotifyHosts#1]
I don't know if its just me but it did not work on my Windows 7 pc. It worked on my Windows 10 laptop and after I upgraded to Windows 10 for other reasons on my pc it worked... May just be my pc but idk

**Comment by anesthetiize** [comment]
Are you logged in into an administrator account on your computer?

You can check this using the following command on a command prompt (terminal) or PowerShell window:

        net user 

If you still have issues, please provide me with the error message you get when running the script.

**Comment by anesthetiize** [comment]
Since that seemed to be the problem, im closing this issue now. 

Best regards.
