### ISSUE TITLE
Google street view not working (blurry)

### ISSUE THREAD

**Issue by tetj** [anesthetiize/SpotifyHosts#2]
Here is how I fixed the problem :
1- open C:\Windows\System32\drivers\etc\hosts using notepad++
2- removed line : 127.0.0.1 geo3.ggpht.com
3- saved file

**Comment by Nyox** [comment]
Wow, thank you !!! That was very helpful, I was searching for a solution for a long time!

**Comment by anesthetiize** [comment]
Made the change on the hosts file. Closing.
